# Generated by Django 2.2.26 on 2022-10-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_apims_baec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimsbaecconnector',
            name='municipality_token',
            field=models.CharField(blank=True, help_text="Token d'identification de l'organisme dans APIMS BAEC", max_length=128, verbose_name="Token d'identification"),
        ),
        migrations.AlterField(
            model_name='apimsbaecconnector',
            name='password',
            field=models.CharField(blank=True, help_text='Mot de passe APIMS BAEC', max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='apimsbaecconnector',
            name='username',
            field=models.CharField(blank=True, help_text='Utilisateur APIMS BAEC', max_length=128, verbose_name='Utilisateur'),
        ),
    ]
